name: Build Main

on:
  push:
    branches:
      - main
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Monday at 23:00:00 UTC (Monday at 15:00:00 PST)
    - cron: "0 23 * * 1"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Lint with flake8
        run: |
          flake8 cdp_scrapers --count --verbose --show-source --statistics
      - name: Check with black
        run: |
          black --check cdp_scrapers

  publish:
    if: "contains(github.event.head_commit.message, 'Bump version')"
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: CouncilDataProject
          password: ${{ secrets.PYPI_TOKEN }}
